os: osx
before_install:
install:
before_script:
  # setup ssh for fastlane match
  # set default identity file
  - |
    cat << EOF >> ~/.ssh/config
    Host *
     AddKeysToAgent yes
     UseKeychain yes
     IdentityFile $PWD/dummy-ssh-keys/key
  # add MATCH_HOST public key to known hosts
  - ssh-keyscan -t ecdsa -p $MATCH_PORT $MATCH_HOST >> ~/.ssh/known_hosts
  - chmod 600 dummy-ssh-keys/key
  - chmod 700 dummy-ssh-keys

  # install fastlane
  - gem install bundler:2.0.1 # this gem file requires bundler 2.0
  - (cd ios; bundle install)

  # install flutter
  - FLUTTER_CHANNEL=stable
#  - FLUTTER_VERSION=1.5.4-hotfix.2-${FLUTTER_CHANNEL} # coincides with local version
  - FLUTTER_VERSION=1.2.1-${FLUTTER_CHANNEL} # coincides with local version
  - wget --quiet --output-document=flutter.zip https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/macos/flutter_macos_v${FLUTTER_VERSION}.zip && unzip -qq flutter.zip > /dev/null && rm flutter.zip
  - export PATH="$PATH":"$PWD/.pub-cache/bin"
  - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor -v

script:
  - cd ios
  - fastlane build_debug