os: osx
before_install:
install:
before_script:
  # setup ssh for fastlane match
  # set default identity file
  - |
    cat << EOF >> ~/.ssh/config
    Host *
     AddKeysToAgent yes
     UseKeychain yes
     IdentityFile $PWD/dummy-ssh-keys/key
  # add MATCH_HOST public key to known hosts
  - ssh-keyscan -t ecdsa -p $MATCH_PORT $MATCH_HOST >> ~/.ssh/known_hosts
  - chmod 600 dummy-ssh-keys/key
  - chmod 700 dummy-ssh-keys

  # install fastlane
  - gem install bundler:2.0.1 # this gem file requires bundler 2.0
  - (cd ios; bundle install)

  # install flutter
  - FLUTTER_CHANNEL=stable
#  - FLUTTER_VERSION=1.5.4-hotfix.2-${FLUTTER_CHANNEL} # coincides with local version
  - FLUTTER_VERSION=1.2.1-${FLUTTER_CHANNEL} # coincides with local version
  - wget --quiet --output-document=flutter.zip https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/macos/flutter_macos_v${FLUTTER_VERSION}.zip && unzip -qq flutter.zip > /dev/null && rm flutter.zip
  - export PATH="$PATH":"$PWD/.pub-cache/bin"
  - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor -v

script:
  - (cd ios && fastlane build_debug)

# deploy debug .app
before_deploy:
  - zip -r Runner.app.zip build/ios/Debug-iphoneos/Runner.app
deploy:
  provider: releases
  api_key:
    secure: DMnHqH12P1jS7LGV9Aar61gfBPwlZF+86Cs2x0e3Ghz5pk3Psx1ykv9lzIm1kQ3ZWVyZmrthXC+wG8UlsKNXEKrXqqfc4fxahji80FUpJPqIpEB24miNF5+z7GLL35fq0YHVRG9HxEXov5Db5vdiGzAzpe9hcHOzxaZcYRGXGool4DMfh82zOCJj/dAUOkJH2CrBglu1OVhDAHHH50tc6RpdwreZG8tFL9N2Y82usB0ewz+wjeHVeQKsxknIhm9Zz8rhXI9SK/TT8pBmg/IfMkzo8CCQLvOhob+AwZT+V2W7d3UEtaDA/C1XO7auIF9MnkX7CNOsGSFnLF2+AyM8d3dw4/nxhJ9s/CW2XDvgwP7AOw64FJXmHSKJAAnvK2PEvZpCh0lgLm5gGI0rNay90omfjaWuGBZPzQiwtWFCPd/ZoFtFaIypvnIAnSt9mCouP77wXyYplx8OAYSRNgFD4DIz8nax4eFQuZz4eg3AyDEuq/UK5iDL3jjYvrWjAT1El+6/0I5/rh3p36FmNDASZxSGKZ5a+Rtxou/UUcE3ftE3vAtOi0VaHQnaRpiKbxy3L0d7M3slBcMVxX0zff3fjvfU0AFhMUO33JdVs2qw4zLc5nOCzXe37+LKHU/AUlT02dNbkViFOg+GTENywMysmtqqdDatWnJG2Gi2ZElc0+c=
  file: Runner.app.zip
  on:
    repo: mmcc007/flutter_ios_build
