os: osx
before_install:
install:
before_script:
  # setup ssh for fastlane match
  # set default identity file
  - |
    cat << EOF >> ~/.ssh/config
    Host *
     AddKeysToAgent yes
     UseKeychain yes
     IdentityFile $PWD/dummy-ssh-keys/key
  # add MATCH_HOST public key to known hosts
  - ssh-keyscan -t ecdsa -p $MATCH_PORT $MATCH_HOST >> ~/.ssh/known_hosts
  - chmod 600 dummy-ssh-keys/key
  - chmod 700 dummy-ssh-keys

  # install fastlane
  - gem install bundler:2.0.1 # this gem file requires bundler 2.0
  - (cd ios; bundle install)

  # install flutter
  - FLUTTER_CHANNEL=stable
#  - FLUTTER_VERSION=1.5.4-hotfix.2-${FLUTTER_CHANNEL} # coincides with local version
  - FLUTTER_VERSION=1.2.1-${FLUTTER_CHANNEL} # coincides with local version
  - wget --quiet --output-document=flutter.zip https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/macos/flutter_macos_v${FLUTTER_VERSION}.zip && unzip -qq flutter.zip > /dev/null && rm flutter.zip
  - export PATH="$PATH":"$PWD/.pub-cache/bin"
  - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor -v

script:
  - (cd ios && fastlane build_debug)

# deploy debug .app
before_deploy:
  - zip -r Runner.app.zip build/ios/Debug-iphoneos/Runner.app
deploy:
  provider: releases
  api_key:
    secure: MpDrQL37qoS3SEVN4tu3+KQGIsNBdtyvse/0WnIE0KBUf4R7nIQ+EDi2GEm371ON/Xgzw4ZcVcb02WA6hH24s5AraS2Pv0Yh34vXzrgP+4c/KkI0d4P+/tztlIpTtOL8+DN43IKBU/bZUDffHb8YG4AsccmDPSrYAH821PZ3Hto9tuL0SFfe75rmAWWMVBKAyL6UqamDFxZqpqdPGy0ey/CQGY7ad6zSdHHUk8O2zwzXo6KsMptBI3jEbN3sFWQOG4F6baUjV5h4oieG2tThZRz3SKApTF2+aLCkiAf66LPIRo6QBMdawg1Zc1smdg8PyIA6DZBEDLS/RX5jdA9wI8/r+R3h6N+FyyUT49yT0xbBUImTx4tzH9DNIB29eYTNPu7FI51JvG2TGAkK4Ckrz2PPdZPMKXnWMQMLsk2BurhCnL6ODT2wZy9uas3/FIr+0ZiwCi9wdNQaqwnkbpCZ9PQN6lNWtcCa5dtD3MF8ZWZOI5aM1UUVMSye9mWXd+k3N89r2cbUr912oDndbO12OAlNg073GjYAu0TsEEQsIIlbDEGG1fYBhAla4hvdMn2DqIBnBIvZH+LgczgNlEkHTt3djv1S3G8W0UAEJwfbxboUHfeCK/H57AglU2hCTzjexGaCuds6oOkmhm8oP5oKJa9bTybZUa7UrLLHD4eE4IA=
  file: Runner.app.zip
  on:
    repo: mmcc007/flutter_ios_build
