os: osx
before_install:
install:
before_script:
  # resolve "SSH: The authenticity of host <host> can't be established"
  - ls -la ~/.ssh
  - cat ~/.ssh/authorized_keys
  - ssh-keygen -t rsa -b 4096 -P '' -C "TravisCIKey" -f ~/.ssh/id_rsa
  - ssh-keyscan -t ecdsa -p $MATCH_PORT $MATCH_IP_ADDRESS
  - ssh-keyscan -t ecdsa -p $MATCH_PORT $MATCH_IP_ADDRESS >> ~/.ssh/known_hosts
  - ls -la ~/.ssh
  - ssh -vT git@$MATCH_IP_ADDRESS -p $MATCH_PORT

  # install fastlane
#  - sudo gem install fastlane -NV
  # install version of fastlane from Gemfile.lock
#  - rvm gemset use global # install bundler to a global gemset (since gem file is in local dir)
  - gem install bundler:2.0.1 # this gem file requires bundler 2.0
  - (cd ios; bundle install)

  # install flutter
  - FLUTTER_CHANNEL=stable
#  - FLUTTER_VERSION=1.5.4-hotfix.2-${FLUTTER_CHANNEL} # coincides with local version
  - FLUTTER_VERSION=1.2.1-${FLUTTER_CHANNEL} # coincides with local version
  - wget --quiet --output-document=flutter.zip https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/macos/flutter_macos_v${FLUTTER_VERSION}.zip && unzip -qq flutter.zip > /dev/null && rm flutter.zip
  - export PATH="$PATH":"$PWD/.pub-cache/bin"
  - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor -v

script:
  - cd ios
  - fastlane --verbose build_debug