os: osx
before_install:
install:
before_script:
  # install fastlane
  - sudo gem install fastlane -NV

  # install flutter
  - FLUTTER_CHANNEL=stable
  - FLUTTER_VERSION=1.5.4-hotfix.2-${FLUTTER_CHANNEL}
  - wget --quiet --output-document=flutter.zip https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/macos/flutter_macos_v${FLUTTER_VERSION}.zip && unzip -qq flutter.zip > /dev/null && rm flutter.zip
  - export PATH="$PATH":"$PWD/.pub-cache/bin"
  - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor -v

script: flutter build ios -t test_driver/main.dart --debug